// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TaskCreator.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ДобавлениеЗадачи_Feature : object, Xunit.IClassFixture<ДобавлениеЗадачи_Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AddTask.feature"
#line hidden
        
        public ДобавлениеЗадачи_Feature(ДобавлениеЗадачи_Feature.FixtureData fixtureData, TaskCreator_Specs_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Добавление задачи.", "Взрослый может добавить задачу. Ребенок добавить задачу не может.\r\nДля создания з" +
                    "адачи текст для данной задачи не должен быть пустой строкой.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Взрослый может добавить задачу")]
        [Xunit.TraitAttribute("FeatureTitle", "Добавление задачи.")]
        [Xunit.TraitAttribute("Description", "Взрослый может добавить задачу")]
        public virtual void ВзрослыйМожетДобавитьЗадачу()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Взрослый может добавить задачу", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Phone",
                            "Name",
                            "Adult"});
                table1.AddRow(new string[] {
                            "father@family.com",
                            "+79180000001",
                            "Папа",
                            "да"});
                table1.AddRow(new string[] {
                            "son@family.com",
                            "+79180000002",
                            "Сын",
                            "нет"});
#line 6
  testRunner.Given("семья из", ((string)(null)), table1, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "TaskID",
                            "Text",
                            "IsCompleted",
                            "DateDeadline"});
                table2.AddRow(new string[] {
                            "8eaf664a-d074-4f9b-9369-8f9e6f0e096a",
                            "Я текст задачи",
                            "false",
                            "30.03.2023"});
                table2.AddRow(new string[] {
                            "4a592327-edc1-4dc6-b1f8-459b65e37a73",
                            "Вторая задача",
                            "true",
                            "31.03.2023"});
#line 10
  testRunner.And("список задач из", ((string)(null)), table2, "And ");
#line hidden
#line 14
     testRunner.And("в систему вошел Папа", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
     testRunner.When("пользователь добавляет задачу \"Новая задача\"(12.04.2023)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
     testRunner.And("пользователь получает список задач", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 17
     testRunner.Then("количество элементов в списке задач 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 18
     testRunner.And("в списке задач есть задача с текстом \"Я текст задачи\" под номером 8eaf664a-d074-4" +
                        "f9b-9369-8f9e6f0e096a", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
     testRunner.And("в списке задач есть задача с текстом \"Вторая задача\" под номером 4a592327-edc1-4d" +
                        "c6-b1f8-459b65e37a73", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
     testRunner.And("в списке задач есть задача с текстом \"Новая задача\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ребенок не может добавить задачу")]
        [Xunit.TraitAttribute("FeatureTitle", "Добавление задачи.")]
        [Xunit.TraitAttribute("Description", "Ребенок не может добавить задачу")]
        public virtual void РебенокНеМожетДобавитьЗадачу()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ребенок не может добавить задачу", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 22
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Phone",
                            "Name",
                            "Adult"});
                table3.AddRow(new string[] {
                            "father@family.com",
                            "+79180000001",
                            "Папа",
                            "да"});
                table3.AddRow(new string[] {
                            "son@family.com",
                            "+79180000002",
                            "Сын",
                            "нет"});
#line 23
     testRunner.Given("семья из", ((string)(null)), table3, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "TaskID",
                            "Text",
                            "IsCompleted",
                            "DateDeadline"});
                table4.AddRow(new string[] {
                            "8eaf664a-d074-4f9b-9369-8f9e6f0e096a",
                            "Я текст задачи",
                            "false",
                            "30.03.2023"});
                table4.AddRow(new string[] {
                            "4a592327-edc1-4dc6-b1f8-459b65e37a73",
                            "Вторая задача",
                            "true",
                            "31.03.2023"});
#line 27
     testRunner.And("список задач из", ((string)(null)), table4, "And ");
#line hidden
#line 31
     testRunner.And("в систему вошел Сын", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
     testRunner.When("пользователь добавляет задачу \"Новая задача\"(12.04.2023)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 33
     testRunner.And("пользователь получает список задач", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
     testRunner.Then("количество элементов в списке задач 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
     testRunner.And("в списке задач есть задача с текстом \"Я текст задачи\" под номером 8eaf664a-d074-4" +
                        "f9b-9369-8f9e6f0e096a", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 36
     testRunner.And("в списке задач есть задача с текстом \"Вторая задача\" под номером 4a592327-edc1-4d" +
                        "c6-b1f8-459b65e37a73", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Взрослый не может добавить задачу без текста")]
        [Xunit.TraitAttribute("FeatureTitle", "Добавление задачи.")]
        [Xunit.TraitAttribute("Description", "Взрослый не может добавить задачу без текста")]
        public virtual void ВзрослыйНеМожетДобавитьЗадачуБезТекста()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Взрослый не может добавить задачу без текста", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 38
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Phone",
                            "Name",
                            "Adult"});
                table5.AddRow(new string[] {
                            "father@family.com",
                            "+79180000001",
                            "Папа",
                            "да"});
                table5.AddRow(new string[] {
                            "son@family.com",
                            "+79180000002",
                            "Сын",
                            "нет"});
#line 39
  testRunner.Given("семья из", ((string)(null)), table5, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "TaskID",
                            "Text",
                            "IsCompleted",
                            "DateDeadline"});
                table6.AddRow(new string[] {
                            "8eaf664a-d074-4f9b-9369-8f9e6f0e096a",
                            "Я текст задачи",
                            "false",
                            "30.03.2023"});
                table6.AddRow(new string[] {
                            "4a592327-edc1-4dc6-b1f8-459b65e37a73",
                            "Вторая задача",
                            "true",
                            "31.03.2023"});
#line 43
  testRunner.And("список задач из", ((string)(null)), table6, "And ");
#line hidden
#line 47
  testRunner.And("в систему вошел Папа", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 48
  testRunner.When("пользователь добавляет задачу \"\"(12.04.2023)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 49
  testRunner.And("пользователь получает список задач", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 50
  testRunner.Then("количество элементов в списке задач 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 51
  testRunner.And("в списке задач есть задача с текстом \"Я текст задачи\" под номером 8eaf664a-d074-4" +
                        "f9b-9369-8f9e6f0e096a", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
  testRunner.And("в списке задач есть задача с текстом \"Вторая задача\" под номером 4a592327-edc1-4d" +
                        "c6-b1f8-459b65e37a73", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ДобавлениеЗадачи_Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ДобавлениеЗадачи_Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
