// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TaskCreator.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ОтменаВыполненияЗадачи_Feature : object, Xunit.IClassFixture<ОтменаВыполненияЗадачи_Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CancelingTask.feature"
#line hidden
        
        public ОтменаВыполненияЗадачи_Feature(ОтменаВыполненияЗадачи_Feature.FixtureData fixtureData, TaskCreator_Specs_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Отмена выполнения задачи.", "Взрослый может отменить выполнение задачи. Ребенок не может отменить выполнение з" +
                    "адачи.\r\nЗадача помечается не выполненной по её id.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Взрослый может отменить выполнение задачи")]
        [Xunit.TraitAttribute("FeatureTitle", "Отмена выполнения задачи.")]
        [Xunit.TraitAttribute("Description", "Взрослый может отменить выполнение задачи")]
        public virtual void ВзрослыйМожетОтменитьВыполнениеЗадачи()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Взрослый может отменить выполнение задачи", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Phone",
                            "Name",
                            "Adult"});
                table7.AddRow(new string[] {
                            "father@family.com",
                            "+79180000001",
                            "Папа",
                            "да"});
                table7.AddRow(new string[] {
                            "son@family.com",
                            "+79180000002",
                            "Сын",
                            "нет"});
#line 6
  testRunner.Given("семья из", ((string)(null)), table7, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "TaskID",
                            "Text",
                            "IsCompleted",
                            "DateDeadline"});
                table8.AddRow(new string[] {
                            "8eaf664a-d074-4f9b-9369-8f9e6f0e096a",
                            "Я текст задачи",
                            "false",
                            "30.03.2023"});
                table8.AddRow(new string[] {
                            "4a592327-edc1-4dc6-b1f8-459b65e37a73",
                            "Вторая задача",
                            "true",
                            "31.03.2023"});
                table8.AddRow(new string[] {
                            "273f4d03-2f65-48f2-92e4-0e25cd28ba56",
                            "Третья задача",
                            "false",
                            "22.03.2023"});
#line 10
  testRunner.And("список задач из", ((string)(null)), table8, "And ");
#line hidden
#line 15
     testRunner.And("в систему вошел Папа", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 16
  testRunner.When("пользователь отменяет выполнение задачи под номером 4a592327-edc1-4dc6-b1f8-459b6" +
                        "5e37a73", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 17
  testRunner.And("пользователь получает список задач", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
  testRunner.Then("количество элементов в списке задач 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
  testRunner.And("в списке задач есть невыполненная задача под номером 8eaf664a-d074-4f9b-9369-8f9e" +
                        "6f0e096a", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
  testRunner.And("в списке задач есть невыполненная задача под номером 4a592327-edc1-4dc6-b1f8-459b" +
                        "65e37a73", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
  testRunner.And("в списке задач есть невыполненная задача под номером 273f4d03-2f65-48f2-92e4-0e25" +
                        "cd28ba56", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ребенок не может отменить выполнение задачи")]
        [Xunit.TraitAttribute("FeatureTitle", "Отмена выполнения задачи.")]
        [Xunit.TraitAttribute("Description", "Ребенок не может отменить выполнение задачи")]
        public virtual void РебенокНеМожетОтменитьВыполнениеЗадачи()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ребенок не может отменить выполнение задачи", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 23
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Phone",
                            "Name",
                            "Adult"});
                table9.AddRow(new string[] {
                            "father@family.com",
                            "+79180000001",
                            "Папа",
                            "да"});
                table9.AddRow(new string[] {
                            "son@family.com",
                            "+79180000002",
                            "Сын",
                            "нет"});
#line 24
  testRunner.Given("семья из", ((string)(null)), table9, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "TaskID",
                            "Text",
                            "IsCompleted",
                            "DateDeadline"});
                table10.AddRow(new string[] {
                            "8eaf664a-d074-4f9b-9369-8f9e6f0e096a",
                            "Я текст задачи",
                            "false",
                            "30.03.2023"});
                table10.AddRow(new string[] {
                            "4a592327-edc1-4dc6-b1f8-459b65e37a73",
                            "Вторая задача",
                            "true",
                            "31.03.2023"});
                table10.AddRow(new string[] {
                            "273f4d03-2f65-48f2-92e4-0e25cd28ba56",
                            "Третья задача",
                            "false",
                            "22.03.2023"});
#line 28
  testRunner.And("список задач из", ((string)(null)), table10, "And ");
#line hidden
#line 33
  testRunner.And("в систему вошел Сын", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
  testRunner.When("пользователь отменяет выполнение задачи под номером 4a592327-edc1-4dc6-b1f8-459b6" +
                        "5e37a73", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 35
  testRunner.And("пользователь получает список задач", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 36
  testRunner.Then("количество элементов в списке задач 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
  testRunner.And("в списке задач есть невыполненная задача под номером 8eaf664a-d074-4f9b-9369-8f9e" +
                        "6f0e096a", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
  testRunner.And("в списке задач есть выполненная задача под номером 4a592327-edc1-4dc6-b1f8-459b65" +
                        "e37a73", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
  testRunner.And("в списке задач есть невыполненная задача под номером 273f4d03-2f65-48f2-92e4-0e25" +
                        "cd28ba56", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Взрослый не может отменить выполнение задачи, если она еще не выполнена")]
        [Xunit.TraitAttribute("FeatureTitle", "Отмена выполнения задачи.")]
        [Xunit.TraitAttribute("Description", "Взрослый не может отменить выполнение задачи, если она еще не выполнена")]
        public virtual void ВзрослыйНеМожетОтменитьВыполнениеЗадачиЕслиОнаЕщеНеВыполнена()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Взрослый не может отменить выполнение задачи, если она еще не выполнена", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 41
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Phone",
                            "Name",
                            "Adult"});
                table11.AddRow(new string[] {
                            "father@family.com",
                            "+79180000001",
                            "Папа",
                            "да"});
                table11.AddRow(new string[] {
                            "son@family.com",
                            "+79180000002",
                            "Сын",
                            "нет"});
#line 42
  testRunner.Given("семья из", ((string)(null)), table11, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "TaskID",
                            "Text",
                            "IsCompleted",
                            "DateDeadline"});
                table12.AddRow(new string[] {
                            "8eaf664a-d074-4f9b-9369-8f9e6f0e096a",
                            "Я текст задачи",
                            "false",
                            "30.03.2023"});
                table12.AddRow(new string[] {
                            "4a592327-edc1-4dc6-b1f8-459b65e37a73",
                            "Вторая задача",
                            "true",
                            "31.03.2023"});
                table12.AddRow(new string[] {
                            "273f4d03-2f65-48f2-92e4-0e25cd28ba56",
                            "Третья задача",
                            "false",
                            "22.03.2023"});
#line 46
  testRunner.And("список задач из", ((string)(null)), table12, "And ");
#line hidden
#line 51
     testRunner.And("в систему вошел Папа", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
  testRunner.When("пользователь отменяет выполнение задачи под номером 8eaf664a-d074-4f9b-9369-8f9e6" +
                        "f0e096a", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 53
  testRunner.And("пользователь получает список задач", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 54
  testRunner.Then("количество элементов в списке задач 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 55
  testRunner.And("в списке задач есть невыполненная задача под номером 8eaf664a-d074-4f9b-9369-8f9e" +
                        "6f0e096a", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 56
  testRunner.And("в списке задач есть выполненная задача под номером 4a592327-edc1-4dc6-b1f8-459b65" +
                        "e37a73", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 57
  testRunner.And("в списке задач есть невыполненная задача под номером 273f4d03-2f65-48f2-92e4-0e25" +
                        "cd28ba56", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ОтменаВыполненияЗадачи_Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ОтменаВыполненияЗадачи_Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
